TypeCraftWords = {
    "sloth", "banana", "forest", "typhoon", "lava", "warrior", "classic", "rogue", "frostbolt",
    "fireball", "arcane", "shadow", "heal", "smite", "shield", "cloak", "dagger", "sword", "axe",
    "mace", "bow", "staff", "wand", "crossbow", "polearm", "spear", "trident", "hammer", "fist",
    "gauntlet", "boots", "gloves", "helmet", "chestplate", "leggings", "bracers", "belt", "ring",
    "amulet", "potion", "elixir", "flask", "bandage", "scroll", "book", "recipe", "glyph",
    "gem", "ore", "herb", "leather", "cloth", "wood", "stone", "iron", "gold", "silver", "copper",
    "platinum", "titanium", "mithril", "thorium", "fel", "nature", "frost", "fire", "wind", "earth",
    "water", "light", "dark", "chaos", "order", "time", "space", "life", "death", "soul", "mind",
    "body", "spirit", "essence", "aura", "barrier", "ward", "totem", "familiar", "pet", "mount",
    "companion", "follower", "ally", "enemy", "neutral", "faction", "guild", "raid", "party",
    "instance", "dungeon", "arena", "battleground", "warfront", "siege", "assault", "defense",
    "attack", "retreat", "victory", "defeat", "honor", "glory", "valor", "reputation", "currency",
    "point", "mark", "badge", "token", "seal", "insignia", "medal", "award", "prize", "treasure",
    "loot", "chest", "bag", "quiver", "pouch", "satchel", "pack", "bundle", "stack", "pile", "heap",
    "cluster", "group", "set", "collection", "series", "edition", "version", "type", "kind", "class",
    "category", "species", "race", "breed", "gender", "age", "level", "rank", "status", "title",
    "name", "alias", "nickname", "moniker", "handle", "tag", "label", "stamp", "signature",
    "inscription", "note", "message", "letter", "document", "file", "record", "report", "log",
    "journal", "diary", "notebook", "sketchbook", "album", "portfolio", "gallery", "exhibit",
    "display", "showcase", "archive", "library", "repository", "storehouse", "warehouse", "depot",
    "vault", "safe", "locker", "cabinet", "drawer", "shelf", "rack", "stand", "table", "desk",
    "counter", "bench", "workbench", "station", "area", "zone", "region", "territory", "province",
    "state", "country", "continent", "planet", "world", "realm", "dimension", "plane", "floor",
    "ceiling", "wall", "door", "window", "gate", "portal", "passage", "tunnel", "hall", "corridor",
    "room", "chamber", "suite", "apartment", "house", "building", "structure", "facility", "complex",
    "campus", "estate", "property", "land", "ground", "lot", "field", "park", "garden", "yard",
    "farm", "ranch", "orchard", "vineyard", "winery", "brewery", "distillery", "factory", "mill",
    "plant", "workshop", "studio", "lab", "office", "store", "shop", "market", "mall", "bazaar",
    "fair", "festival", "event", "celebration", "gathering", "meeting", "conference", "seminar",
    "lecture", "class", "course", "training", "lesson", "study", "research", "experiment", "test",
    "quiz", "exam", "assessment", "evaluation", "review", "analysis", "presentation", "proposal",
    "plan", "strategy", "tactic", "method", "technique", "approach", "process", "procedure",
    "system", "framework", "model", "theory", "concept", "idea", "notion", "belief", "opinion",
    "view", "perspective", "standpoint", "attitude", "mindset", "philosophy", "ethic", "value",
    "principle", "rule", "law", "regulation", "policy", "guideline", "standard", "criterion",
    "benchmark", "measure", "indicator", "sign", "signal", "cue", "prompt", "hint", "clue",
    "suggestion", "recommendation", "advice", "counsel", "guidance", "direction", "instruction",
    "order", "command", "request", "demand", "appeal", "petition", "application", "offer", "bid",
    "tender", "quotation", "estimate", "valuation", "appraisal", "audit", "inspection", "survey",
    "investigation", "probe", "inquiry", "question", "query", "interrogation", "examination",
    "trial", "simulation", "prototype", "sample", "specimen", "example", "case", "instance",
    "illustration", "demonstration", "exemplification", "performance", "act", "scene", "play",
    "drama", "musical", "opera", "ballet", "concert", "recital", "spectacle", "occasion",
    "happening", "incident", "episode"
}
